export const CREATE_POKEMON = 'CREATE_POKEMON';
export const CREATE_POKEMON_SUCCESS = 'CREATE_POKEMON_SUCCESS';
export const CREATE_POKEMON_ERROR = 'CREATE_POKEMON_ERROR';

export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_SUCCESS = 'GET_POKEMONS_SUCCESS';
export const GET_POKEMONS_ERROR = 'GET_POKEMONS_ERROR';

export const GET_DETAIL = 'GET_DETAIL';
export const GET_DETAIL_SUCCESS = 'GET_DETAIL_SUCCESS';
export const GET_DETAIL_ERROR = 'GET_DETAIL_ERROR';

export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const SEARCH_POKEMON_SUCCESS = 'SEARCH_POKEMON_SUCCESS';
export const SEARCH_POKEMON_ERROR = 'SEARCH_POKEMON_ERROR';

export const GET_TYPES = 'GET_TYPES';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_ERROR = 'GET_TYPES_ERROR';

